name: 'clickhouse_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'clickhouse_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  clickhouse_analytics:
    # All models will be materialized as tables by default
    +materialized: table
    +on_schema_change: "append_new_columns"

    # Staging models - direct from source
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]

    # Intermediate models - business logic transformations
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ["intermediate"]

    # Mart models - final analytics-ready tables
    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]
      # Use incremental materialization for large fact tables
      core:
        +materialized: table
      metrics:
        +materialized: table

# Test configurations
tests:
  clickhouse_analytics:
    +store_failures: true
    +schema: test_results

# Snapshot configurations
snapshots:
  clickhouse_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Documentation
docs-paths: ["docs"]

# Variables for the project
vars:
  # Date range for incremental models
  start_date: '2024-01-01'

  # Flags for different environments
  is_dev: true

  # Business logic variables
  active_customer_days: 90
  high_value_threshold: 1000
