version: '3'

includes:
  dbt: ./dbt
  airflow: ./airflow
  database: ./database

tasks:
  setup:
    description: |
      Set up all relevant resources
    cmds:
      - cd dbt && task setup && cd -
      - cd airflow && task setup && cd -
      - cd database && task setup && cd -
  
  reset-venvs:
    description: |
      Removes all existing virtual environments
    cmds:
      - rm -rf dbt/venv
      - rm -rf airflow/venv
      - rm -rf database/venv