version: '3'

env:
  VENV_NAME: '{{.VENV_NAME | default "venv"}}'

tasks:
  install-local:
    description: |
      Install clickhouse via. curl
    cmds:
      - |
        if [ -e clickhouse ]; then
          echo "clickhouse file already exists, not installing"
        else
          curl https://clickhouse.com/ | sh
        fi

  setup:
    description: |
      Setup virtual environment and install packages
    cmds:
      - python3 -m venv ${VENV_NAME}
      - task: update
  
  update:
    description: |
      Install requirements
    cmds:
      - |
        source ${VENV_NAME}/bin/activate
        pip3 install -r requirements/requirements.txt

  start:
    description: |
      go-task runs everything in a custom shell, so things like activating virtual environments are not possible.
      This task is mostly for printing the commands required for preparing your environment for dbt. `init.sh`
      runs `eval $(task start)` to activate the virtual environment
    cmds:
      - echo "source ${VENV_NAME}/bin/activate"
      