version: '3'

env:
  VENV_NAME: '{{.VENV_NAME | default "venv"}}'

tasks:
  install:
    description: |
      Install clickhouse via. curl
    cmds:
      - |
        if [ -e clickhouse ]; then
          echo "clickhouse file already exists, not installing"
        else
          curl https://clickhouse.com/ | sh
        fi

  setup:
    description: |
      Setup virtual environment and install packages
    cmds:
      - task: install
      - python3 -m venv ${VENV_NAME}
      