
version: '3'

env:
  VENV_NAME: '{{.VENV_NAME | default "venv"}}'
  AIRFLOW_HOME: ./airflow
  AIRFLOW_VERSION: 2.9.2
  PYTHON_VERSION: 3.12

tasks:
  setup:
    description: |
      Create virtual environment and install airflow
    cmds:
      - python3 -m venv ${VENV_NAME}
      - task: update
  
  update:
    description: |
      Install requirements
    cmds:
      - | 
        source ${VENV_NAME}/bin/activate
        pip3 install "apache-airflow==${AIRFLOW_VERSION}" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
        pip3 install -r requirements/requirements.txt

  start:
    description: |
      go-task runs everything in a custom shell, so things like activating virtual environments are not possible.
      This task is mostly for printing the commands required for preparing your environment for dbt. `init.sh`
      runs `eval $(task start)` to activate the virtual environment
    cmds:
      - echo "source ${VENV_NAME}/bin/activate"
