
version: '3'

env:
  VENV_NAME: '{{.VENV_NAME | default "venv"}}'
  AIRFLOW_HOME: ./airflow
  AIRFLOW_VERSION: 2.9.2
  PYTHON_VERSION: 3.12

tasks:
  setup:
    description: |
      Create virtual environment and install airflow
    cmds:
      - python3 -m venv ${VENV_NAME}
      - task: update
  
  update:
    description: |
      Install requirements
    cmds:
      - ${VENV_NAME}/bin/pip3 install "apache-airflow==${AIRFLOW_VERSION}" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
      - ${VENV_NAME}/bin/pip3 install -r requirements.txt


