version: 2

sources:
  - name: staging
    description: Raw data loaded from CSV files into ClickHouse staging schema
    database: analytics
    schema: staging
    tables:
      - name: customers
        description: Customer master data
        columns:
          - name: customer_id
            description: Unique identifier for customers
            tests:
              - unique
              - not_null
          - name: customer_name
            description: Full name of the customer
          - name: email
            description: Customer email address
            tests:
              - not_null
          - name: country
            description: Customer's country
          - name: signup_date
            description: Date when customer signed up
            tests:
              - not_null
          - name: is_active
            description: Flag indicating if customer is active (1) or inactive (0)

      - name: products
        description: Product catalog
        columns:
          - name: product_id
            description: Unique identifier for products
            tests:
              - unique
              - not_null
          - name: product_name
            description: Name of the product
          - name: category
            description: Product category
          - name: price
            description: Selling price of the product
            tests:
              - not_null
          - name: cost
            description: Cost of the product
          - name: created_at
            description: Timestamp when product was created

      - name: orders
        description: Customer orders
        columns:
          - name: order_id
            description: Unique identifier for orders
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Foreign key to customers table
            tests:
              - not_null
          - name: order_date
            description: Date of the order
            tests:
              - not_null
          - name: order_timestamp
            description: Exact timestamp of the order
          - name: total_amount
            description: Total order amount
            tests:
              - not_null
          - name: status
            description: Order status (completed, processing, cancelled)
            tests:
              - accepted_values:
                  values: ['completed', 'processing', 'cancelled', 'pending']

      - name: order_items
        description: Line items for each order
        columns:
          - name: order_item_id
            description: Unique identifier for order items
            tests:
              - unique
              - not_null
          - name: order_id
            description: Foreign key to orders table
            tests:
              - not_null
          - name: product_id
            description: Foreign key to products table
            tests:
              - not_null
          - name: quantity
            description: Quantity ordered
            tests:
              - not_null
          - name: unit_price
            description: Price per unit
          - name: discount_percent
            description: Discount percentage applied
